FPS = 60
TORCHES_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/torch'
COINS_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/coin'
CHESTS_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/chest'
PLAYERS_DIR = 'tiles/2D Pixel Dungeon Asset Pack/Character_animation/priests_idle/priest3/v2'
INTERFACE_DIR = 'tiles/2D Pixel Dungeon Asset Pack/interface'
FLASKS_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/flasks'
SLASH_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/Sword Slashes'
ITEMS_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/RPG Items 16x16 Pack 1'
KEYS_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/keys'
FLAG_DIR = 'tiles/2D Pixel Dungeon Asset Pack/items and trap_animation/flag'
SKULL_DIR = 'tiles/2D Pixel Dungeon Asset Pack/Character_animation/monsters_idle/skull/v2'
SPRITE_SIZE = 16
PLAYER_SPEED = 120   # [px/fps]
PLAYER_SPEED /= FPS  # [px] - изменение координат за кадр
